import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { COLORS } from "../constants/colors";
import MainNav from "./MainNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={geistSans.className} style={{ background: COLORS.background }}>
        <MainNav />
        <div className="w-full">
          {children}
        </div>
      </body>
    </html>
  );
}

// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { COLORS } from "../constants/colors";
// import Link from "next/link";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// function MainNav() {
//   return (
//     <nav className="w-full bg-black flex items-center justify-between px-8 py-4 shadow-lg z-50 border-b border-gray-800">
//       <Link href="/" className="flex items-center gap-3 hover:opacity-80 transition-opacity">
//         <img src="/logo.svg" alt="Vecros Logo" className="h-10 w-10" />
//         <span className="text-white text-2xl font-bold tracking-wider">VECROS</span>
//       </Link>
//       <ul className="flex gap-8 text-white font-medium text-base">
//         <li><Link href="/" className="hover:text-[#0070F3] transition-colors duration-200">Home</Link></li>
//         <li><Link href="/landing1" className="hover:text-[#0070F3] transition-colors duration-200">Landing 1</Link></li>
//         <li><Link href="/landing2" className="hover:text-[#0070F3] transition-colors duration-200">Landing 2</Link></li>
//       </ul>
//     </nav>
//   );
// }

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={geistSans.className} style={{ background: COLORS.background }}>
//         <MainNav />
//         {children}
//       </body>
//     </html>
//   );
// }
